/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PokerApi": {
      "type": "sst.aws.AppSync"
      "url": string
    }
    "PokerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}